version: '3.5'

networks:
  kraken:
    name: "kraken"

services:
  kraken-container-one:
    labels:
      com.octoperf/taskId: ${KRAKEN_TASK_ID}
      com.octoperf/taskType: GATLING_RECORD
      com.octoperf/containerName: ${KRAKEN_TASK_ID}-container-one
      com.octoperf/hostId: hostId
      com.octoperf/label: Container One
      com.octoperf/description: ${KRAKEN_DESCRIPTION}
      com.octoperf/expectedCount: ${KRAKEN_EXPECTED_COUNT}
      com.octoperf/applicationId: ${KRAKEN_APPLICATION_ID}
      com.octoperf/userId: ${KRAKEN_USER_ID}
    container_name: ${KRAKEN_TASK_ID}-container-one_STARTING
    image: ${KRAKEN_IMAGE}
    networks:
      - kraken

  kraken-container-two:
    labels:
      com.octoperf/taskId: ${KRAKEN_TASK_ID}
      com.octoperf/taskType: GATLING_RECORD
      com.octoperf/containerName: ${KRAKEN_TASK_ID}-container-two
      com.octoperf/hostId: hostId
      com.octoperf/label: Container Two
      com.octoperf/description: ${KRAKEN_DESCRIPTION}
      com.octoperf/expectedCount: ${KRAKEN_EXPECTED_COUNT}
      com.octoperf/applicationId: ${KRAKEN_APPLICATION_ID}
      com.octoperf/userId: ${KRAKEN_USER_ID}
    container_name: ${KRAKEN_TASK_ID}-container-two_STARTING
    image: ${KRAKEN_IMAGE}
    networks:
      - kraken