apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-administration-ui
spec:
  ports:
    - port: {{ .Values.frontend.administration.service.port }}
      targetPort: {{ .Values.frontend.administration.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "name" . }}-administration-ui
subsets:
  - addresses:
      - ip: {{ .Values.frontend.administration.ip }}
    ports:
      - port: {{ .Values.frontend.administration.port }}