apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "name" . }}-backend
subsets:
  - addresses:
      - ip: {{ .Values.backend.ip }}
    ports:
      - port: {{ .Values.backend.port }}